AllCops:
  TargetRubyVersion: '2.4.1'
  EnabledByDefault: true
  UseCache: false

Rails:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Enabled: false
  Max: 100

Metrics/ModuleLength:
  Enabled: false
  Max: 100

Metrics/MethodLength:
  Enabled: false
  Max: 10

Metrics/ParameterLists:
  Enabled: false
  Max: 5

Metrics/BlockLength:
  Enabled: false
  Max: 50

Metrics/AbcSize:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Layout/AlignArray:
  Enabled: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/MethodCallWithArgsParentheses:
  Enabled: false
  IgnoredMethods:
    - puts

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true

Style/InlineComment:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  Enabled: false
